# Generated by Django 6.1.1 on 2026-09-17 23:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('tipo', models.CharField(choices=[('PC', 'Computador'), ('IMP', 'Impresora'), ('RED', 'Equipo de red'), ('OTR', 'Otro')], default='PC', max_length=3, verbose_name='Tipo')),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Compra')),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('REP', 'En reparación'), ('BAJ', 'De baja')], default='ACT', max_length=3, verbose_name='Estado')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento')),
            ],
        ),
    ]
